### ISSUE TITLE
Blue connection lines are not animated on IE

### ISSUE THREAD

**Issue by TestArmyQA** [beacondig/Landing-Page-aon-2020#11]
![2gUAmuFLCs](https://user-images.githubusercontent.com/59614014/74530558-9da0c000-4f2a-11ea-8d95-0b70cfb9eaca.png)

**Comment by TestArmyQA** [comment]
Lines are still not animated

**Comment by Diksha-Beacon** [comment]
I have removed the animation CSS intentionally only for IE because it creates an issue in IE and i discussed with denis regarding the same.

**Comment by TestArmyQA** [comment]
ok, I am closing this ticket
